CREATE TABLE OWNERS (
    ID         INTEGER IDENTITY PRIMARY KEY,
    FIRSTNAME  VARCHAR(30),
    LASTNAME   VARCHAR(30),
    ADDRESS    VARCHAR(255),
    CITY       VARCHAR(80),
    TELEPHONE  VARCHAR(20)
);
